#!/usr/bin/env python

# Resolve path configuration
import os
import sys
import importlib
import argparse
import json

root = os.path.join(os.path.dirname(__file__), "..")
learning_data_path = os.path.join(root, "learning_data")
sys.path.append(root)
sys.path.append(learning_data_path)

# Start script code from here
from learning_data.generator.hole_evaluator import HoleEvaluator
from pypokerengine.engine.card import Card
import random
import csv
import time

def parse_args():
  parser = argparse.ArgumentParser(description="Set test data configuration")
  parser.add_argument("--simulation", type=int, required=True, help="times of simulation")
  parser.add_argument("--player", type=int, required=True, help="number of player in simulation")
  args = parser.parse_args()
  if args.simulation <= 0 or args.player <= 1:
    raise Exception("Invalid args")
  return args.simulation, args.player

def generate_data(simulation_num, player_num):
  data = []
  for hole1_card_id in range(1, 52):
    for hole2_card_id in range(hole1_card_id+1, 53):
      hole = [Card.from_id(hole1_card_id), Card.from_id(hole2_card_id)]
      row = [str(card) for card in hole]
      row.append(HoleEvaluator.estimate_win_rate(hole, player_num, simulation_num))
      data.append(row)
  return data

def save_data(file_path, data):
  with open(file_path, 'w') as f:
    writer = csv.writer(f, lineterminator='\n')
    writer.writerows(data)

def gen_file_path(simulation_num, player_num):
  file_name = "%d-simulation-%d-players-win-rate-data.csv" % (simulation_num, player_num)
  return os.path.join(learning_data_path, "data", "win_rate", file_name)

def main():
  start_time = time.time()
  simulation, player = parse_args()
  data = generate_data(simulation, player)
  save_data(gen_file_path(simulation, player), data)
  print "Execution time : %f (s)" % (time.time() - start_time)

if __name__ == '__main__':
  main()
