#!/usr/bin/env python

# Resolve path configuration
import os
import sys
import importlib
import argparse
import json

root = os.path.join(os.path.dirname(__file__), "..")
learning_data_path = os.path.join(root, "learning_data")
sys.path.append(root)
sys.path.append(learning_data_path)

# Start script code from here
from learning_data.generator.hole_evaluator import HoleEvaluator
from pypokerengine.engine.card import Card
import random
import csv
import time

def parse_args():
  parser = argparse.ArgumentParser(description="Set test data configuration")
  parser.add_argument("--n", type=int, required=True, help="number of data to generate")
  args = parser.parse_args()
  return args.n

def generate_data(data_num_for_each_pair):
  data = []
  for hole1_card_id in range(1, 52):
    for hole2_card_id in range(hole1_card_id+1, 53):
      for _ in range(data_num_for_each_pair):
        hole = [Card.from_id(hole1_card_id), Card.from_id(hole2_card_id)]
        data.append(HoleEvaluator.eval_hole(hole))
  return data

def save_data(file_path, data):
  with open(file_path, 'w') as f:
    writer = csv.writer(f, lineterminator='\n')
    writer.writerows(data)

def gen_file_path(data_num):
  file_name = "%d-data-at-%s.csv" % (data_num, time.time())
  return os.path.join(learning_data_path, "data", file_name)

def main():
  start_time = time.time()
  data_num = parse_args()
  data = generate_data(data_num)
  save_data(gen_file_path(data_num), data)
  print "Execution time : %f (s)" % (time.time() - start_time)

if __name__ == '__main__':
  main()
