#!/usr/bin/env python

# Resolve path configuration
import os
import sys
import importlib
import argparse
import json

root = os.path.join(os.path.dirname(__file__), "..")
learning_data_path = os.path.join(root, "learning_data")
sys.path.append(root)
sys.path.append(learning_data_path)

# Start script code from here
from learning_data.generator.hole_evaluator import HoleEvaluator
from pypokerengine.engine.card import Card
import random
import csv
import time

def parse_args():
  parser = argparse.ArgumentParser(description="Set test data configuration")
  parser.add_argument("--n", type=int, required=True, help="number of data to generate")
  args = parser.parse_args()
  return args.n

def generate_data(num):
  data = []
  card_id_range = range(1, 53)
  for _ in range(num):
    hole = [Card.from_id(cid) for cid in random.sample(card_id_range, 2)]
    data.append(HoleEvaluator.eval_hole(hole))
    print data[-1]  # For debug
  return data

def save_data(file_path, data):
  with open(file_path, 'w') as f:
    writer = csv.writer(f, lineterminator='\n')
    writer.writerows(data)

def gen_file_path(data_num):
  file_name = "%d-data-at-%s.csv" % (data_num, time.time())
  return os.path.join(learning_data_path, "data", file_name)

def main():
  data_num = parse_args()
  data = generate_data(data_num)
  save_data(gen_file_path(data_num), data)

if __name__ == '__main__':
  main()
