#!/usr/bin/env python

# HOW TO USE
# ./run_model --model_directory_path ../holecard_handicapper/model/handicapper_fitting/5_layer

# Resolve path configuration
import os
import sys
import importlib
import argparse
import json

root = os.path.join(os.path.dirname(__file__), "..")
module_root_path = os.path.join(root, "holecard_handicapper")
sys.path.append(root)
sys.path.append(module_root_path)

# Start script code from here
from keras.models import model_from_json
from keras.optimizers import SGD, Adam, RMSprop
from holecard_handicapper.training.model_tester import ModelTester

def parse_args():
  parser = argparse.ArgumentParser(description="Receive path of model builder")
  parser.add_argument("--model_directory_path", required=True, help="path to directory which include your model")
  args = parser.parse_args()
  return args.model_directory_path

def load_model(directory_path):
  arrchitecture_path = os.path.join(directory_path, 'model_arrchitecture.json')
  weights_path = os.path.join(directory_path, 'model_weights.h5')
  with open(arrchitecture_path) as f:
    model = model_from_json(f.read())
    model.load_weights(weights_path)
    model.compile(RMSprop(), 'mse')
  return model

def main():
  model_dir_path = parse_args()
  model = load_model(model_dir_path)
  tester = ModelTester()
  print tester.run_popular_test_case(model)

if __name__ == '__main__':
  main()
